name: C/C++ CI

on: [push]

jobs:
  build-windows:
    name: Windows
    runs-on: [windows-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: |
        pwd
        cd build
        cmake --build . -j
        cmake --build . --target install
    - name: test
      run: ctest
      
  build-linux:
    name: Linux
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: make
      run: |
        pwd
        cd build
        cmake --build . -j
        cmake --build . --target install
    - name: test
      run: ctest

