name: Build, unittest, compress

on: [push]

jobs:
  build-windows:
    name: Windows
    runs-on: [windows-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=installWindows-Github ..
    - name: make
      run: |
        cd build
        cmake --build . -j
        cmake --build . --target install
    - name: test
      run: |
        cd build
        ctest
    - name: compress
      run: Compress-Archive -DestinationPath installWindows-Github.zip -Path build/installWindows-Github
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: windows_install
        path: installWindows-Github.zip
      
  build-linux:
    name: Linux
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=installLinux-Github ..
    - name: make
      run: |
        cd build
        cmake --build . -j
        cmake --build . --target install
    - name: test
      run: |
        cd build
        ctest
    - name: compress
      run: tar -czvf installLinux-Github.tar.gz build/installLinux-Github
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: linux_install
        path: installLinux-Github.tar.gz

