name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: python waf configure --prefix=install
    - name: make
      run: python waf install
